### ISSUE TITLE
[Docs] Possible outdated documentation

### ISSUE THREAD

**Issue by wesleytanws** [google/hs-portray#7]
We have identified **`1`** possible instance of outdated documentation:

- [ ] [`prettyShow`](https://github.com/google/hs-portray/blob/6af2a5c888a530a6578ab51d1ff594c172d17b78/portray-pretty/src/Data/Portray/Pretty.hs#L37) was renamed to [`showPortrayal`](https://github.com/google/hs-portray/blob/e9c5f635785432bb70d39497362cbd5dee66cbd3/portray-pretty/src/Data/Portray/Pretty.hs#L83) but the change has not been reflected in the current version of the [README](https://github.com/google/hs-portray/blob/ae27b04cbc1ce209d961770dfd7e3e1eef59c51e/README.md) file

#### About
This is part of a research project that aims to automatically detect outdated documentation in GitHub repositories. We are evaluating the validity of our approach by identifying instances of outdated documentation in real-world projects.

We hope that this research will be a step towards keeping documentation up-to-date. If this has been helpful, consider updating the documentation to keep it in sync with the source code. If this has not been helpful, consider updating this issue with an explanation, so that we can improve our approach. Thanks!

**Comment by wesleytanws** [comment]
Friendly ping :)

**Comment by awpr** [comment]
Cool idea, and it seems to have worked as intended here, thanks!  I seem to have had notifications misconfigured for this repo, so I only noticed this when I found it on the GitHub UI.
